# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gioditalia
email: innavoig92@gmail.com
description: "The journal of a programmer. :octocat:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gioditalia.github.io" # the base hostname & protocol for your site
twitter_username: gioditalia
github_username:  gioditalia
repository_name: gioditalia.github.io
paginate: 5

gems: [jekyll-paginate, kramdown, jemoji]
# Build settings
markdown: kramdown
